### ISSUE TITLE
Kanban board Setup ROR group capstone

### ISSUE THREAD

**Issue by Kel-nana** [Kel-nana/final_group_capstone_front_end#22]
### Kanban board Setup

- Team members [ 4 ] ;

1. [`Hussein Hashi`](https://github.com/husush23)
2. [`Junaid Syed`](https://github.com/iamsjunaid)
3. [`Nahid Raihan`](https://github.com/Nahid1911)
4. [`Kelvin Irungu`](https://github.com/Kel-nana)

## Links to the repositories

1. [Frontend](https://github.com/Kel-nana/Final_group_capstone_front_end) 
2. [Backend](https://github.com/Kel-nana/Final_group_capstone_backend)
3. [Kanban-board](https://github.com/users/Kel-nana/projects/6)

- Kanban template screenshot
![Kanban board screenshot](https://github.com/Kel-nana/Final_group_capstone_front_end/assets/61676854/41cc161d-2d75-4e42-a93a-ae0569a7712c)

**Comment by Meltrust** [comment]
Hi @Kel-nana,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All cards have been assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] According to the project requirements:

![image](https://github.com/Kel-nana/Final_group_capstone_front_end/assets/57421823/a1fa8729-e466-4492-b0e7-60a669df7442)

At the time of this review, these are the pointings:

@Nahid1911 22
@Kel-nana 35
@iamsjunaid 36
@husush23 22

As you can see, @Kel-nana and @iamsjunaid have a lot more points than @Nahid1911 and @husush23.  The maximum difference allowed is 5 points.

Therefore, kindly make it so no team member has 5 more points than any other member.

That way, we will meet this particular [requirement](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @Kel-nana ,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Pointings are now equal according to the spec✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
